[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements (red is ed0030).
primaryColor = "#fcf400"

# Background color for the main content area.
backgroundColor = "#005e23"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#569e29"

# Color used for almost all text.
textColor = "#ffffff"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"